-- Specialty Burger: database setup / migration
-- Run this entire file in Supabase SQL Editor.
-- It creates the tables, RLS policies, and loads the complete 35-item menu.
-- Product images are stored as /menu/... paths so both Website and Dashboard can resolve them.

create extension if not exists pgcrypto;

create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists (select 1 from public.admin_users where user_id=auth.uid()); $$;

create table if not exists public.categories (id text primary key,name text not null,name_ar text not null default '',image text not null default '',enabled boolean not null default true,sort_order integer not null default 1,created_at timestamptz not null default now());
create table if not exists public.products (id text primary key,name text not null,name_ar text not null default '',description text not null default '',price numeric(10,2) not null default 0,discount_price numeric(10,2),category_id text references public.categories(id) on update cascade on delete set null,image text not null default '',available boolean not null default true,featured boolean not null default false,bestseller boolean not null default false,is_new boolean not null default false,prep_time integer not null default 10,calories integer,created_at timestamptz not null default now());
create index if not exists products_category_id_idx on public.products(category_id);

create table if not exists public.orders (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.customers (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.offers (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.reviews (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.notifications (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.website_content (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
create table if not exists public.restaurant_settings (id text primary key,data jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());


alter table public.admin_users enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.customers enable row level security;
alter table public.offers enable row level security;
alter table public.reviews enable row level security;
alter table public.notifications enable row level security;
alter table public.website_content enable row level security;
alter table public.restaurant_settings enable row level security;

drop policy if exists "admins read self" on public.admin_users;
create policy "admins read self" on public.admin_users for select using (auth.uid()=user_id);
drop policy if exists "public read categories" on public.categories;
create policy "public read categories" on public.categories for select using (true);
drop policy if exists "admins write categories" on public.categories;
create policy "admins write categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read products" on public.products;
create policy "public read products" on public.products for select using (true);
drop policy if exists "admins write products" on public.products;
create policy "admins write products" on public.products for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins all orders" on public.orders;
create policy "admins all orders" on public.orders for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins all customers" on public.customers;
create policy "admins all customers" on public.customers for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins all offers" on public.offers;
create policy "admins all offers" on public.offers for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins all reviews" on public.reviews;
create policy "admins all reviews" on public.reviews for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins all notifications" on public.notifications;
create policy "admins all notifications" on public.notifications for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read website content" on public.website_content;
create policy "public read website content" on public.website_content for select using (true);
drop policy if exists "admins all website_content" on public.website_content;
create policy "admins all website_content" on public.website_content for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "public read restaurant settings" on public.restaurant_settings;
create policy "public read restaurant settings" on public.restaurant_settings for select using (true);
drop policy if exists "admins all restaurant_settings" on public.restaurant_settings;
create policy "admins all restaurant_settings" on public.restaurant_settings for all using (public.is_admin()) with check (public.is_admin());

-- Product uploads are public-read but remain writable only by dashboard admins.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-images', 'product-images', true, 5242880, '{image/jpeg,image/png,image/webp}')
on conflict (id) do update set public=true, file_size_limit=5242880, allowed_mime_types='{image/jpeg,image/png,image/webp}';

drop policy if exists "public read product images" on storage.objects;
create policy "public read product images" on storage.objects for select using (bucket_id='product-images');
drop policy if exists "admins upload product images" on storage.objects;
create policy "admins upload product images" on storage.objects for insert with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admins update product images" on storage.objects;
create policy "admins update product images" on storage.objects for update using (bucket_id='product-images' and public.is_admin()) with check (bucket_id='product-images' and public.is_admin());
drop policy if exists "admins delete product images" on storage.objects;
create policy "admins delete product images" on storage.objects for delete using (bucket_id='product-images' and public.is_admin());

-- Remove the earlier 9-item seed IDs so the final menu has exactly 35 products.
delete from public.products where id in ('p-original','p-pomegranate','p-caramel','p-fried-chicken','p-fries','p-wings','p-broast','p-strips-meal','p-coke');

-- Categories
delete from public.categories where lower(name) = 'crepe';
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('appetizers','Appetizers','المقبلات','/menu/extra-4.jpg',true,1) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('burgers','Burgers','البرجر','/menu/burger-1.jpg',true,2) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('broast','Broast','بروست','/menu/meal-3.jpg',true,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('meals','Meals','الوجبات','/menu/meal-1.jpg',true,4) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('addons','Sauces & Add-ons','صوصات وإضافات','/menu/ext1.jpg',true,5) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;
insert into public.categories(id,name,name_ar,image,enabled,sort_order) values ('drinks','Drinks','المشروبات','/menu/drink-1.jpg',true,6) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,image=excluded.image,enabled=excluded.enabled,sort_order=excluded.sort_order;

-- Complete 35-item menu (same IDs/names/images as the website source)
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('original-specialty','Original Specialty','اوريجينال سبيشالتي','Pretzel bun, fresh grilled beef patty, cheese, lettuce, white onion, tomato, special sauce',26,'burgers','/menu/burger-1.jpg',true,false,true,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('wood-beef','Wood Beef Burger','برجر لحم الحطب','Pretzel bun, wood-fired fresh beef patty, lettuce, cheese, special sauce',24,'burgers','/menu/burger-2.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('pomegranate','Pomegranate Speciality','سبيشاليتي الرمان','Pretzel bun, fresh grilled beef, cheese, pomegranate, rocca, mayo and pomegranate molasses',27,'burgers','/menu/burger-3.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('caramelized-onion','Caramelized Onion Burger','برجر البصل المكرمل','Pretzel bun, fresh beef patty, cheese, caramelized onions, special sauce',25,'burgers','/menu/burger-4.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('bacon','Bacon Burger','برجر البيكون','Pretzel bun, fresh beef patty, cheese, beef bacon, special sauce',27,'burgers','/menu/burger-5.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('bbq-specialty','BBQ Specialty','باربكيو سبيشالتي','Pretzel bun, fresh grilled beef, potato sticks, cheese, lettuce, tomato, BBQ sauce',25,'burgers','/menu/burger-6.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('fried-chicken','Fried Chicken Breast Burger','برجر صدر الدجاج المقلي','Pretzel bun, fried fresh chicken breast, cheese, lettuce, coleslaw, special sauce',24,'burgers','/menu/burger-7.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('grilled-chicken','Grilled Chicken Breast Burger','برجر صدر الدجاج المشوي','Pretzel bun, grilled fresh chicken, cheese, lettuce, white onion, tomato, special sauce',24,'burgers','/menu/burger-8.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('spicy-220','Spicy Burger 220','برجر حار 220','Pretzel bun, fried fresh chicken breast, cheese, lettuce, tomato, hot sriracha sauce',24,'burgers','/menu/burger-9.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('wood-chicken','Wood-fired Chicken Burger','برجر دجاج الحطب','Pretzel bun, wood-fired fresh chicken, lettuce, cheese, special sauce',24,'burgers','/menu/burger-10.jpg',true,false,false,false,12) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('chicken-proust','Chicken Broast','دجاج بروست','Four pieces of crispy broasted chicken — regular or spicy',18,'broast','/menu/meal-3.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('chicken-strips','Chicken Strips','دجاج ستربس','Five pieces of crispy chicken strips',17,'broast','/menu/extra-10.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('slow-strips','Slow Strips Meal','وجبة سلو ستربس','4 crispy chicken strips served with fries, coleslaw and a soft drink',26,'meals','/menu/meal-1.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('kids','Kids Meal','وجبة الأطفال','Chicken nuggets (4 pcs) served with french fries and apple juice',17,'meals','/menu/meal-2.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('fries','French Fries','بطاطس مقلية','Crispy french fries served with our special seasoning',6,'appetizers','/menu/extra-4.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('cheese-fries','Cheese Fries','بطاطس بالجبنة','Crispy fries topped with cheese sauce',10,'appetizers','/menu/extra-13.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('chi-fries','Chi Fries','تشي فرايز','Crispy chicken pieces over fries with cheese sauce, jalapeño and Cheetos',25,'appetizers','/menu/extra-9.jpg',true,false,true,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('chili-fries','Chili Fries','تشيلي فرايز','Crispy fries with minced beef, jalapeño, tomato, spring onion and cheese sauce',25,'appetizers','/menu/extra-11.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('coleslaw','Coleslaw','سلطة الملفوف','Carrot, cabbage, mayonnaise',6,'appetizers','/menu/extra-1.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('rocca-pomegranate','Rocca Pomegranate Salad','سلطة الجرجير بالرمان','Rocca, pomegranate, tomato, white onion, special dressing',13,'appetizers','/menu/extra-2.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('caesar','Caesar Salad','سلطة سيزر','Romaine lettuce, Caesar dressing, croutons and cheese',18,'appetizers','/menu/extra-3.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('onion-rings','Crispy Golden Onion Rings','حلقات البصل الذهبية المقرمشة','Crispy golden onion rings',12,'appetizers','/menu/extra-5.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('mozzarella-sticks','Mozzarella Cheese Sticks (5 PC)','أصابع جبنة الموزريلا (٥ قطع)','Mozzarella sticks, crispy outside and melty inside',18,'appetizers','/menu/extra-6.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('nuggets','Chicken Nuggets (5 PC)','ناجت الدجاج (٥ قطع)','Crispy chicken nuggets',15,'appetizers','/menu/extra-7.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('jalapeno-cheese','Jalapeño Cheese (5 PC)','هالابينو تشيز (٥ قطع)','Fried spicy jalapeño bites with creamy cheddar cheese',19,'appetizers','/menu/extra-8.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('chicken-wings','Chicken Wings','أجنحة الدجاج','3 chicken wings with your choice of sauce: spicy or BBQ',14,'appetizers','/menu/extra-12.jpg',true,false,false,false,8) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('fanta','Fanta Orange','فانتا برتقال','Chilled soft drink can',3,'drinks','/menu/drink-1.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('coke-light','Coca-Cola Light','كوكاكولا دايت','Chilled soft drink can',3,'drinks','/menu/drink-2.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('sprite','Sprite','سبرايت','Chilled soft drink can',3,'drinks','/menu/drink-3.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('coke','Coca-Cola Classic','كوكاكولا كلاسيك','Chilled soft drink can',3,'drinks','/menu/drink-4.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('peach-ice-tea','Peach Iced Tea','الشاي المثلج بالخوخ','Refreshing peach iced tea',5,'drinks','/menu/drink-5.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('pomegranate-juice','Fresh Pomegranate Juice','عصير الرمان الطازج','100% fresh pomegranate juice',15,'drinks','/menu/drink-6.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('orange-juice','Fresh Orange Juice','عصير البرتقال الطازج','100% fresh orange juice',15,'drinks','/menu/drink-7.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('water','Mineral Water','مياه معدنية','Chilled mineral water',1,'drinks','/menu/drink-8.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;
insert into public.products(id,name,name_ar,description,price,category_id,image,available,featured,bestseller,is_new,prep_time) values ('mojito','Blueberry / Watermelon Mojito','موهيتو توت أزرق / بطيخ','Refreshing blueberry or watermelon mojito',12,'drinks','/menu/drink-9.jpg',true,false,false,false,3) on conflict(id) do update set name=excluded.name,name_ar=excluded.name_ar,description=excluded.description,price=excluded.price,category_id=excluded.category_id,image=excluded.image,available=excluded.available,featured=excluded.featured,bestseller=excluded.bestseller,is_new=excluded.is_new,prep_time=excluded.prep_time;

insert into public.website_content(id,data) values ('main','{"heroTitle":"رحلة نكهات لا تنسى","heroSubtitle":"لحم بقري بلدي طازج، خبز بريتزل يخبز يومياً، وصوصات من مطبخنا. كل قضمة تحكي طعم.","heroImage":"/images/restaurant-background.jpg","restaurantDescription":"برجر على أصوله في جدة.","whatsapp":"","phone":"","address":"جدة، المملكة العربية السعودية","footer":"Specialty Burger","openingHours":"","instagram":"@specialtyburger","snapchat":"@specialtyburger"}') on conflict(id) do nothing;
insert into public.restaurant_settings(id,data) values ('main','{"name":"Specialty Burger","logo":"/logo.png","favicon":"/favicon.png","minimumOrder":25,"deliveryFee":10,"deliveryTime":35,"pickup":true,"delivery":true,"status":"open"}') on conflict(id) do nothing;